version: 2

models:
  - name: table1
    description: "This is the main source table with id, name, and updated_at."
    columns:
      - name: id
        description: "Primary key identifier for table1"
        tests:
          - unique
          - not_null
      - name: name
        description: "Name of the entity"
        tests:
          - not_null
      - name: updated_at
        description: "Timestamp of last update"
        tests:
          - not_null